### ISSUE TITLE
YOUR IDEAS

### ISSUE THREAD

**Issue by nimamoslemy** [nimamoslemy/ventilator#1]
please write your comments and ideas

**Comment by AbnusTech** [comment]
سلام لطفا علاقمند به همکاری هستیم. تماس بگیرید با من ۰۹۱۲۱۴۴۲۰۲۹

**Comment by nimamoslemy** [comment]
سلام،مسلمی هستم.


ممنون از پاسخ تون


درباره پروژه ،این یک پروژه درس سه واحدی بیو دیزاین دانشکده مهندسی پزشکی امیرکبیر که توسط پنج گروه در مرحله ایده و طراحی هستش که با تایید شدن ایده در مرکز نوآوری دانشکده روی اون کار میشه.


اگر مایلید اسم و رشته و دانشگاه تون رو بفرمایید تا با تایید استاد مربوطه به ما ملحق بشید.


باز هم تشکر از مشارکتتون




On Sun, May 3, 2020 at 8:18 AM +0430, "AbnusTech" <notifications@github.com> wrote:
















سلام لطفا علاقمند به همکاری هستیم. تماس بگیرید با من ۰۹۱۲۱۴۴۲۰۲۹
